name: 루비/레일스를 사용하는 서비스 모임
url: https://rorlakr.github.io/rubyworld
markdown: kramdown
highlighter: pygments
timezone: Asia/Seoul
cache: bundler
exclude:
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- vendor
- .travis.yml
- .rspec
- .gitignore
- spec
